"""empty message

Revision ID: 57b6cf276bfe
Revises: c35bb5efbd57
Create Date: 2023-06-28 04:31:20.602511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57b6cf276bfe'
down_revision = 'c35bb5efbd57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('temp_otp', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'user', ['email'], ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('temp_otp', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
