"""empty message

Revision ID: 0eb9ef997079
Revises: 57b6cf276bfe
Create Date: 2023-07-06 10:44:56.720743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0eb9ef997079'
down_revision = '57b6cf276bfe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_name', sa.String(length=50), nullable=False))
        batch_op.drop_column('test')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test', sa.INTEGER(), nullable=True))
        batch_op.drop_column('event_name')

    # ### end Alembic commands ###
