"""empty message

Revision ID: 8cda4f2832cf
Revises: d51285caa725
Create Date: 2023-07-08 01:20:14.998287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cda4f2832cf'
down_revision = 'd51285caa725'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('event_name', sa.String(length=50), nullable=False),
    sa.Column('event_pic', sa.String(length=100), nullable=False),
    sa.Column('event_date', sa.String(length=50), nullable=False),
    sa.Column('about_event', sa.String(length=500), nullable=False),
    sa.Column('team', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('event_name'),
    sa.UniqueConstraint('event_pic')
    )
    op.create_table('temp_user',
    sa.Column('fname', sa.String(length=50), nullable=False),
    sa.Column('lname', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('mobile', sa.Integer(), nullable=False),
    sa.Column('roll', sa.Integer(), nullable=True),
    sa.Column('password', sa.String(length=500), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('stream', sa.String(length=10), nullable=True),
    sa.Column('exp', sa.Integer(), nullable=True),
    sa.Column('otp', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('mobile'),
    sa.UniqueConstraint('roll')
    )
    op.create_table('user',
    sa.Column('fname', sa.String(length=50), nullable=False),
    sa.Column('lname', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('mobile', sa.Integer(), nullable=False),
    sa.Column('roll', sa.Integer(), nullable=True),
    sa.Column('password', sa.String(length=500), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('stream', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('email', 'mobile'),
    sa.UniqueConstraint('roll')
    )
    op.create_table('deleted_users',
    sa.Column('fname', sa.String(length=50), nullable=False),
    sa.Column('lname', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('mobile', sa.Integer(), nullable=False),
    sa.Column('roll', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('stream', sa.String(length=10), nullable=True),
    sa.Column('deleted_by', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['deleted_by'], ['user.email'], ),
    sa.PrimaryKeyConstraint('email', 'mobile'),
    sa.UniqueConstraint('roll')
    )
    op.create_table('participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('roll', sa.Integer(), nullable=False),
    sa.Column('event_name', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['event_name'], ['event.event_name'], ),
    sa.ForeignKeyConstraint(['roll'], ['user.roll'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team_participate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('roll', sa.Integer(), nullable=False),
    sa.Column('event_name', sa.String(length=50), nullable=False),
    sa.Column('team_name', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['event_name'], ['event.event_name'], ),
    sa.ForeignKeyConstraint(['roll'], ['user.roll'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('temp_otp',
    sa.Column('login_email', sa.String(length=100), nullable=True),
    sa.Column('otp', sa.Integer(), nullable=False),
    sa.Column('exp_time', sa.Integer(), nullable=True),
    sa.Column('password', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['login_email'], ['user.email'], ),
    sa.PrimaryKeyConstraint('login_email')
    )
    op.create_table('winers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('roll', sa.Integer(), nullable=True),
    sa.Column('team', sa.String(length=100), nullable=True),
    sa.Column('event_name', sa.String(length=100), nullable=False),
    sa.Column('winers', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_name'], ['event.event_name'], ),
    sa.ForeignKeyConstraint(['roll'], ['user.roll'], ),
    sa.ForeignKeyConstraint(['team'], ['team_participate.team_name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('winers')
    op.drop_table('temp_otp')
    op.drop_table('team_participate')
    op.drop_table('participants')
    op.drop_table('deleted_users')
    op.drop_table('user')
    op.drop_table('temp_user')
    op.drop_table('event')
    # ### end Alembic commands ###
