"""empty message

Revision ID: c35bb5efbd57
Revises: 
Create Date: 2023-06-28 04:27:54.463914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c35bb5efbd57'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('temp_otp_temp_user',
    sa.Column('temp_otp_email', sa.String(length=100), nullable=True),
    sa.Column('temp_user_email', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['temp_otp_email'], ['temp_otp.email'], ),
    sa.ForeignKeyConstraint(['temp_user_email'], ['temp_otp.email'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('temp_otp_temp_user')
    # ### end Alembic commands ###
